---
swagger: "2.0"
info:
  title: A simple demo API that runs along with a Prometheus app
  version: "1"
basePath: /
produces:
  - application/json
paths:
  /:
    get:
      operationId: app.index
      responses:
        "200":
          description: A hello world like operation
          schema:
            type: string
